name: ql_archive
description: Encrypted QorLab archive (.ql) format utilities (no-cloud portability).
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.10.7

dependencies:
  cryptography: ^2.7.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

